INSERT INTO  CARD VALUES(101,'党刘涛','四班')
INSERT INTO  CARD VALUES(102,'陈启航','四班')
INSERT INTO  CARD VALUES(103,'张家豪','四班')
INSERT INTO  CARD VALUES(104,'梁壮壮','四班')
INSERT INTO  CARD VALUES(105,'徐龙溪','四班')
INSERT INTO  CARD VALUES(106,'王大个','三班')
INSERT INTO  CARD VALUES(107,'王老板','三班')
INSERT INTO  CARD VALUES(108,'万俊辉','三班')
INSERT INTO  CARD VALUES(109,'刘长江','四班')
INSERT INTO  CARD VALUES(110,'田淞丹','三班')
INSERT INTO  CARD VALUES(111,'徐广慧','三班')
INSERT INTO  CARD VALUES(112,'王文正','四班')
INSERT INTO  CARD VALUES(113,'张吉森','四班')
INSERT INTO  CARD VALUES(114,'陈俊成','四班')
INSERT INTO  CARD VALUES(115,'孙玉峰','四班')
INSERT INTO  CARD VALUES(116,'梁哲','四班')
INSERT INTO  CARD VALUES(117,'张戈','四班')
INSERT INTO  CARD VALUES(118,'李孟松','三班')
INSERT INTO  CARD VALUES(119,'杨留洋','三班')
INSERT INTO  CARD VALUES(120,'谢明洋','三班')




















