--1.查询部门名称是‘SALES’的员工信息 
SELECT *
from DEPT q
 WHERE q.DNAME='SALES'
--2.查询公司中薪水最高的员工信息 
SELECT MAX(S.SAL)
FROM EMP S
SELECT *
FROM EMP Q
 WHERE Q.SAL=(SELECT MAX(S.SAL)
FROM EMP S)

--3.查询各部门中最高薪水的员工编号，姓名… 
SELECT MAX(E.SAL)
FROM EMP E
 GROUP BY E.DEPTNO 
 SELECT Q.EMPNO,Q.ENAME
 FROM EMP Q
 WHERE Q.SAL IN(SELECT MAX(E.SAL)
FROM EMP E
 GROUP BY E.DEPTNO )
--4.查询各部门最高薪水的员工信息 
 SELECT MAX(Q.SAL)
 FROM EMP Q
 GROUP BY Q.DEPTNO
 SELECT  *
 FROM EMP E
  WHERE E.SAL IN (SELECT MAX(Q.SAL)
 FROM EMP Q
  GROUP BY Q.DEPTNO) 

--5.查询薪水大于该部门平均薪水的员工信息
 

--6.查询部门名称是‘SALES’的员工信息 
SELECT *
from DEPT q
 WHERE q.DNAME='SALES'
--7.查询领导者是‘BLAKE’的员工信息 
SELECT e.EMPNO
from EMP e
 WHERE e.ENAME='BLAKE'
 SELECT *
 FROM EMP W
  WHERE W.MGR=(SELECT e.EMPNO
from EMP e
 WHERE e.ENAME='BLAKE')
--8.查询和SMITH工作相同的员工信息 
 SELECT Q.JOB
 FROM EMP Q
  WHERE Q.ENAME='SMITH'
  SELECT *
  FROM EMP W
   WHERE W.JOB=( SELECT Q.JOB
 FROM EMP Q
  WHERE Q.ENAME='SMITH')

--9.查询平均工资比10部门低的部门编号 
SELECT AVG(F.SAL)
FROM EMP F
 WHERE F.DEPTNO='10'
 SELECT W.DEPTNO
 FROM EMP W
 GROUP BY W.DEPTNO
  HAVING AVG(W.SAL)<(SELECT AVG(F.SAL)
FROM EMP F
 WHERE F.DEPTNO='10')
	

--10.查询在NEW YORK工作的所有员工 
SELECT Q.DEPTNO
FROM DEPT Q
 WHERE Q.DNAME='NEWYORK'


