
--2、写SQL文建立考试成绩表，包括学生姓名，学生学号，考试科目，考试成绩
  -- 并插入20条数据
  insert into sss(name,xuehao,kaoshi,chengji)values('陈启航','1704','语文','80')
    insert into sss(name,xuehao,kaoshi,chengji)values('梁壮壮','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('党刘涛','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('徐龙溪','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('李佳康','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('徐诗雨','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('梁哲','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('张戈','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('徐方位','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('刘博','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('余圣杰','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('尚塞塞','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('陈俊成','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('孙玉峰','1704','语文','80')
      insert into sss(name,xuehao,kaoshi,chengji)values('张济森','1704','语文','60')
      insert into sss(name,xuehao,kaoshi,chengji)values('王文政','1704','语文','70')
      insert into sss(name,xuehao,kaoshi,chengji)values('刘万通','1704','语文','90')
      insert into sss(name,xuehao,kaoshi,chengji)values('张家豪','1704','语文','85')
      insert into sss(name,xuehao,kaoshi,chengji)values('刘长江','1704','语文','62')
      insert into sss(name,xuehao,kaoshi,chengji)values('尚魏杰','1704','语文','59')
      insert into sss(name,xuehao,kaoshi,chengji)values('琪尔康','1704','语文','96')