insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟',17001,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟2',17002,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟3',17003,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟4',17004,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟5',17005,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟6',17006,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟7',17007,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟8',17008,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟9',17009,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟10',170010,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟11',170011,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟12',170012,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟13',170013,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟14',170014,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟15',170015,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟16',170016,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟17',170017,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟18',170018,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟19',170019,'语数英物理化政历生',689)
insert into chengjibiao (xueshengxingming,xueshengxuehao,kaoshikemu,kaoshichengji)values ('久远飞鸟20',170020,'语数英物理化政历生',689)

select * from chengjibiao